### ISSUE TITLE
Go segmentfault when compiling etcd in curvefs, the machine is stuck

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1278]
**Describe the bug (描述bug)**

1、mount curvefs
2、clone curve 
3、bash replace-curve-repo.sh

cd thirdparties/etcdclient && make clean && make all
4、
![image](https://user-images.githubusercontent.com/67582932/163372056-788797bd-cf25-41ef-ba52-098c98ec46d6.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
**go cmd md5sum check**

`after make install go
`curvefs：
/mnt/lxc/pubt1/curve/thirdparties/etcdclient$ md5sum tmp/go/bin/go
e54b6abda144554d352e6dce5f3deb15  tmp/go/bin/go

local：
curve/thirdparties/etcdclient/tmp$ md5sum go/bin/go
e54b6abda144554d352e6dce5f3deb15  go/bin/go

**Comment by ilixiaocui** [comment]
https://elixir.bootlin.com/linux/v4.9.65/source/fs/fuse/file.c#L179：
<img width="572" alt="image" src="https://user-images.githubusercontent.com/15689619/163804132-2c305912-9c77-4454-bc6d-7d6ab4649f60.png">
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/15689619/163804185-f4de9078-39d9-4feb-8155-e7fd8a1801cf.png">

**Comment by ilixiaocui** [comment]
```
write(1, "/mnt/lxc/pubt1/curve/thirdpartie"..., 254/mnt/lxc/pubt1/curve/thirdparties/etcdclient/tmp/go/bin/go build -buildmode=c-shared -o libetcdclient.so /mnt/lxc/pubt1/curve/thirdparties/etcdclient/tmp/gosrc/src/etcdclient.go /mnt/lxc/pubt1/curve/thirdparties/etcdclient/tmp/gosrc/src/objectManager.go
) = 254
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7ffb6cd7b9d0) = 1972359
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, go tool compile: exit status 2
1152921504338411520 5776
fatal error: MStats vs MemStatsType size mismatch

goroutine 1 [running, locked to thread]:
runtime.throw(0xe6a2f4, 0x24)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000092768 sp=0xc000092738 pc=0x42cbe2
runtime.init.3()
	/usr/local/go/src/runtime/mstats.go:428 +0x7e fp=0xc000092788 sp=0xc000092768 pc=0x4287ce
runtime.init()
	<autogenerated>:1 +0x5e fp=0xc000092798 sp=0xc000092788 pc=0x458bce
runtime.main()
	/usr/local/go/src/runtime/proc.go:147 +0xba fp=0xc0000927e0 sp=0xc000092798 pc=0x42e3fa
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000927e8 sp=0xc0000927e0 pc=0x45ae81

Message from syslogd@pubbeta2-curve9 at Apr 19 20:22:25 ...
 kernel:[121636.350046] page:ffffcef7b08df180 count:0 mapcount:0 mapping:ffff99592e70f2a0 index:0x0

Message from syslogd@pubbeta2-curve9 at Apr 19 20:22:25 ...
 kernel:[121636.350076] flags: 0x17fffc000000000()
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 1972359
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1972359, si_uid=2010, si_status=1, si_utime=18, si_stime=12} ---
rt_sigreturn({mask=[]})                 = 1972359
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
read(4, "# Locale name alias data base.\n#"..., 4096) = 2995
read(4, "", 4096)                       = 0
close(4)                                = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(1, "Makefile:37: recipe for target '"..., 54Makefile:37: recipe for target 'libetcdclient' failed
) = 54
write(2, "make: *** [libetcdclient] Error "..., 34make: *** [libetcdclient] Error 1
) = 34
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
chdir("/mnt/lxc/pubt1/curve/thirdparties/etcdclient") = 0
close(1)                                = 0
exit_group(2)                           = ?
+++ exited with 2 +++
```

**Comment by ilixiaocui** [comment]
I tested the compilation of etcdclient on kernel versions 5.4 and 5.10 respectively：

On 5.10-kernel, compile success: 
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/15689619/165203913-bbc658b1-595e-41be-8ae9-311a243024d1.png">

On 5.4-kernel, compile fail:
the crash stack is the same as befor.
