### ISSUE TITLE
mdtest run too long in 7*24h test

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1553]
**Describe the bug (描述bug)**
<img width="1729" alt="image" src="https://user-images.githubusercontent.com/15689619/172562859-d48b7d1d-928e-4532-a60e-97b10f5777ba.png">
mdtest didn't run for 8 days.

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Let's first see what the process is doing through gdb.

NO datacache to flush
```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
---Type <return> to continue, or q <return> to quit---
#1  0x00007ff4b099c50c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000559fb0bffd5e in curvefs::client::S3ClientAdaptorImpl::BackGroundFlush (this=0x7ff4aa312310) at curvefs/src/client/s3/client_s3_adaptor.cpp:282
```

No task need upload
```
#7  0x0000559fb0b6a716 in curve::common::TaskThreadPool<bthread::Mutex, bthread::ConditionVariable>::Take (this=0x7ff4aa312528) at ./src/common/concurrent/task_thread_pool.h:159
```

Wait for trim cache
```
```

**Comment by ilixiaocui** [comment]
```
I 2022-06-08T17:22:31.560447+0800 500719 fuse_client.cpp:453] FuseOpMkDir, parent: 1274623690040, name: dir.mdtest.3.129999, mode: 493

I 2022-06-08T17:24:02.725178+0800 805306 fuse_client.cpp:287] FuseOpOpen, ino: 1274568778046
I 2022-06-08T17:24:02.753949+0800 500719 fuse_s3_client.cpp:286] FuseOpFlush, ino: 1274568778046
I 2022-06-08T17:24:02.754019+0800 500719 fuse_s3_client.cpp:324] FuseOpFlush, ino: 1274568778046 flush ok
I 2022-06-08T17:24:02.754043+0800 500719 fuse_client.cpp:1089] FuseOpRelease, ino: 1274568778046
I 2022-06-08T17:24:02.754885+0800 500719 fuse_client.cpp:1108] FuseOpRelease, ino: 1274568778046 success

I 2022-06-08T17:45:13.619499+0800 1884268 fuse_client.cpp:469] FuseOpRmDir, parent: 1274623690039, name: dir.mdtest.2.0

I 2022-06-08T18:24:59.571871+0800 805306 fuse_client.cpp:469] FuseOpRmDir, parent: 1274623690040, name: dir.mdtest.2.129999
I 2022-06-08T18:24:59.616923+0800 1885323 fuse_s3_client.cpp:234] FuseOpCreate, parent: 1274623690039, name: file.mdtest.2.0, m
ode: 33188
I 2022-06-08T18:24:59.642628+0800 1885323 fuse_client.cpp:287] FuseOpOpen, ino: 1274552055618
I 2022-06-08T18:24:59.644580+0800 1884311 fuse_s3_client.cpp:286] FuseOpFlush, ino: 1274552055618
I 2022-06-08T18:24:59.644613+0800 1884311 fuse_s3_client.cpp:324] FuseOpFlush, ino: 1274552055618 flush ok
I 2022-06-08T18:24:59.644632+0800 1884311 fuse_client.cpp:1089] FuseOpRelease, ino: 1274552055618
I 2022-06-08T18:24:59.645610+0800 1884311 fuse_client.cpp:1108] FuseOpRelease, ino: 1274552055618 success
I 2022-06-08T18:24:59.649412+0800 1884309 fuse_s3_client.cpp:234] FuseOpCreate, parent: 1274623690039, name: file.mdtest.0.0, m
ode: 33188
I 2022-06-08T18:24:59.654598+0800 1884309 fuse_client.cpp:287] FuseOpOpen, ino: 1274590198602
I 2022-06-08T18:24:59.656620+0800 1884268 fuse_s3_client.cpp:286] FuseOpFlush, ino: 1274590198602
I 2022-06-08T18:24:59.656659+0800 1884268 fuse_s3_client.cpp:324] FuseOpFlush, ino: 1274590198602 flush ok

I 2022-06-08T19:16:04.993867+0800 523777 fuse_s3_client.cpp:324] FuseOpFlush, ino: 1274653730109 flush ok
I 2022-06-08T19:16:04.993916+0800 1884309 fuse_client.cpp:1089] FuseOpRelease, ino: 1274653730109
I 2022-06-08T19:16:04.994637+0800 1884309 fuse_client.cpp:1108] FuseOpRelease, ino: 1274653730109 success
I 2022-06-08T23:16:08.047808+0800 523777 fuse_client.cpp:287] FuseOpOpen, ino: 1274568778046
```

**Comment by ilixiaocui** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/15689619/172658892-01cb4366-c9bb-417c-ac3f-d58e1163c8fc.png">
<img width="848" alt="image" src="https://user-images.githubusercontent.com/15689619/172659120-e74645f1-4f30-4cf2-90b5-5edcf04b9c67.png">

**Comment by ilixiaocui** [comment]
Next, to confirm the behavior of mdtest, we use strace to trace system calls related to file operations. Execute the following command.
```
strace -tt -o /outputfile -f -i -e trace=file mpirun --allow-run-as-root -np 4 mdtest -z 2 -b 3 -I 10000 -d /dir
```

**Comment by ilixiaocui** [comment]
<img width="919" alt="image" src="https://user-images.githubusercontent.com/15689619/173172802-fa398b74-d875-4582-b885-a13004551139.png">
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/15689619/173172817-42a14dec-a7c2-454c-9f63-e1662a834d90.png">
