### ISSUE TITLE
[curve/tools-v2]: curve bs delete file raises panic

### ISSUE THREAD

**Issue by lng2020** [opencurve/curve#2402]
**Describe the bug (描述bug)**

`curve bs delete file` failed to delete file

**To Reproduce (复现方法)**

```bash
curve_ops_tool create --fileName=/test --userName=root
curve bs delete file --filename=/test --user=root
```
then it will raise panic

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: Ubuntu20.04
Compiler: 
branch: master
commit id:

**Additional context/screenshots (更多上下文/截图)**
log 
```bash
root@5bf3486a47c4:/# ./root/curve bs delete file --filename=/test --user=root
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda830a]

goroutine 1 [running]:
github.com/opencurve/curve/tools-v2/pkg/config.GetBsAddrSlice(0xc0003a2c80, {0x1042391, 0x7})
        /root/go/src/github.com/opencurve/curve/tools-v2/pkg/config/bs.go:268 +0x8a
github.com/opencurve/curve/tools-v2/pkg/config.GetBsMdsAddrSlice(0xc0003a2c80)
        /root/go/src/github.com/opencurve/curve/tools-v2/pkg/config/bs.go:288 +0x69
github.com/opencurve/curve/tools-v2/pkg/cli/command/curvebs/delete/file.(*DeleteCommand).Init(0xc00019ca20, 0xc0003a2c80, {0xc000293480, 0x0, 0x2})
        /root/go/src/github.com/opencurve/curve/tools-v2/pkg/cli/command/curvebs/delete/file/file.go:47 +0x96
github.com/opencurve/curve/tools-v2/pkg/cli/command.NewFinalCurveCli.func1(0xc0003a2c80, {0xc000293480, 0x0, 0x2})
        /root/go/src/github.com/opencurve/curve/tools-v2/pkg/cli/command/base.go:114 +0xaa
github.com/spf13/cobra.(*Command).execute(0xc0003a2c80, {0xc000293460, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0xb27
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042f180)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x8cb
github.com/spf13/cobra.(*Command).Execute(0xc00042f180)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918 +0x2f
github.com/opencurve/curve/tools-v2/pkg/cli.Execute()
        /root/go/src/github.com/opencurve/curve/tools-v2/pkg/cli/curvecli.go:83 +0x74
main.main()
        /root/go/src/github.com/opencurve/curve/tools-v2/cmd/curve/main.go:30 +0x17
```

**Comment by lng2020** [comment]
The issue is related to the AddFlag function in /tools-v2/pkg/cli/command/delete/file.go not registering the flags required for RPC communication. Consequently, when obtaining mdsAddrs in the Init function, it could lead to a failure in GetBsAddrSlice in /tools-v2/pkg/config/bs.go. Registering the flags for RPC communication in the Init function fix the issue . Additionally,  you might think about adding some checks to the flag retrieval functions in /tools-v2/pkg/config/bs.go.
**before**
```go
func (deleteCommand *DeleteCommand) AddFlags() {
	config.AddBsFilenameRequiredFlag(deleteCommand.Cmd)
	config.AddBsUsernameRequiredFlag(deleteCommand.Cmd)
	config.AddBsPasswordOptionFlag(deleteCommand.Cmd)
	config.AddBsForceDeleteOptionFlag(deleteCommand.Cmd)
}
```
**after**
```go
func (deleteCommand *DeleteCommand) AddFlags() {
	// add flags for RPC
	config.AddFsMdsAddrFlag(deleteCommand.Cmd)
	config.AddRpcTimeoutFlag(deleteCommand.Cmd)
	config.AddRpcRetryTimesFlag(deleteCommand.Cmd)

	config.AddBsFilenameRequiredFlag(deleteCommand.Cmd)
	config.AddBsUsernameRequiredFlag(deleteCommand.Cmd)
	config.AddBsPasswordOptionFlag(deleteCommand.Cmd)
	config.AddBsForceDeleteOptionFlag(deleteCommand.Cmd)
}
```
