### ISSUE TITLE
`curve bs status etcd` runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Xinlong-Chen** [opencurve/curve#2431]
/**Describe the bug (描述bug)**
When I use docker to run curve-tools-v2, it's right for other commands.  
However, when I run `curve bs status etcd`, I get a panic....
```
root@f8df310173eb:/# ./curve bs status mds
+----------------+----------------+------------------------------+----------+
|      ADDR      |   DUMMYADDR    |           VERSION            |  STATUS  |
+----------------+----------------+------------------------------+----------+
| 127.0.0.1:6701 | 127.0.0.1:7701 | v2.1.0-beta+09566f57+release | follower |
+----------------+----------------+                              +          +
| 127.0.0.1:6702 | 127.0.0.1:7702 |                              |          |
+----------------+----------------+                              +----------+
| 127.0.0.1:6700 | 127.0.0.1:7700 |                              | leader   |
+----------------+----------------+------------------------------+----------+
root@f8df310173eb:/# ./curve bs status etcd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa40d7b]

goroutine 15 [running]:
github.com/opencurve/curve/tools-v2/pkg/cli/command.httpGet({0xc000241920, 0x1f}, 0x1dcd6500, 0xa7dd6a?, 0xc000102240?)
	/home/xinlong/curve/tools-v2/pkg/cli/command/base.go:235 +0x19b
created by github.com/opencurve/curve/tools-v2/pkg/cli/command.QueryMetric
	/home/xinlong/curve/tools-v2/pkg/cli/command/base.go:182 +0xcf
```

**To Reproduce (复现方法)**
follow the [work flow](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md), and run the `curve bs status etcd` command in docker.
docker img: harbor.cloud.netease.com/curve/curvebs:playground

**Expected behavior (期望行为)**
behavior like [reference document](https://github.com/opencurve/curve/tree/master/tools-v2#staus-etcd)

**Versions (各种版本)**
OS: debian11
Compiler: go version go1.20.3 linux/amd64
branch: master
commit id: d0beaab94926735eb43eaa183d3eb895edf6fd68

**Additional context/screenshots (更多上下文/截图)**

**Comment by Xinlong-Chen** [comment]
using template.yaml, it seems that the etcd string have a useless blank:

https://github.com/opencurve/curve/blob/b9b6bfdfebb7cad2331dc39c8126bc3f7961d345/tools-v2/pkg/config/template.yaml#L11

---

We need a more **robust** string processing algorithm!
